version: '3.9'

services:
  hr_assistant_bot:
    build:
      context: .
    container_name: hr-assistant-bot
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    restart: always